[project]
name = "llm-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["numpy", "typer", "rich"]

[project.scripts]
llmscratch = "llmscratch.cli:app"